# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  sdkman: joshdholtz/sdkman@0.2.0

jobs:
  arm64-native:
    machine:
      image: ubuntu-2004:current
      resource_class: arm.medium
    steps:
      - checkout
      - sdkman/setup-sdkman
      - sdkman/sdkman-install:
          candidate: java
          version: 21.0.1-graalce
      - run:
          name: "mvnw -Pnative spring-boot:build-image"
          command: "./mvnw -Pnative spring-boot:build-image"
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKERHUB_PASSWORD
      - docker/push:
          image: bjoggis/linode4j
          tag: $CIRCLE_TAG-aarch_64

workflows:
  arm64-native-workflow:
    jobs:
      - arm64-native:
          context:
            - bjoggis-dockerhub
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/